apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}
  labels:
    app: {{ .Values.appName}}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.appName}}
  template:
    metadata:
      labels:
        app: {{ .Values.appName}}
    spec:
      containers:
      - name: {{ .Values.appName}}
        image: {{ .Values.image}}
        ports:
        - containerPort: {{ .Values.port}}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name}}
        - secretRef:
            name: {{ .Values.secrets.name}}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory}}
            cpu: {{ .Values.resources.requests.cpu}}
          limits:
            memory: {{ .Values.resources.limits.memory}}
            cpu: {{ .Values.resources.limits.cpu}}