apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-aws
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws
    kind: SecretStore
  target:
    name: external-secret-prod
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: postgre
      property: db_url