kind: Secret 
apiVersion: v1 
metadata:
  name: secret-dev
data:
  DB_HOST: MTkyLjE2OC4wLjE4
  DB_USER: ZGJ1c2Vy
  DATABASE_PASSWORD: cGFzc3dvcmQxMjM=
  DB_DATABASE: YXBwZGF0YWJhc2U=
  DB_PORT: MjM0NQ==
type: Opaque