version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: appdatabase
    ports:
      - 2345:5432
    volumes:
      - db:/var/lib/postgres
volumes: 
  db: