apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-prod
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: alerts
    notifications.argoproj.io/subscribe.on-deployed.slack: alerts
    notifications.argoproj.io/subscribe.on-health.degraded: alerts
spec:
  destination:
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: helm
    repoURL: 'https://github.com/yigitf/nodeapp.git'
    targetRevision: prod
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
