apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: denemeapp
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://github.com/yigitf/nodeapp.git'
    targetRevision: "1.16.0"
    chart: helm01
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
